GET http://localhost:5005/api/chats/user/all HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2QyYzY3ZjM3ZjRhNTBlYWZkYjZmNjMiLCJlbWFpbCI6InNtaXRAZmdtYWlsLmNvbSIsImlhdCI6MTY3NTE0Nzg1NywiZXhwIjoxNjc1MTUxNDU3fQ.YjcaNdPCnrErETG4MTA29mQ0wjBUH8A8e_faZoCQxpo