
export default {
    SEND_NEW_MESSAGE_REQUEST: 'SEND_NEW_MESSAGE_RQUEST',
    SEND_NEW_MESSAGE_SUCCESS: 'SEND_NEW_MESSAGE_SUCCESS',
    SEND_NEW_MESSAGE_ERROR: 'SEND_NEW_MESSAGE_ERROR',
    LOGIN_USER_REQUEST:'LOGIN_USER_REQUEST',
    LOGIN_USER_SUCCESS:'LOGIN_USER_SUCCESS',
    LOGIN_USER_ERROR:'LOGIN_USER_ERROR',
    REGISTER_USER_REQUEST:'REGISTER_USER_REQUEST',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_ERROR:'REGISTER_USER_ERROR',
    USER_CHATS_REQUEST:'USER_CHATS_REQUEST',
    USER_CHATS_SUCCESS: 'USER_CHATS_SUCCESS',
    USER_CHATS_ERROR:'USER_CHATS_ERROR',
    GET_CHAT_WITH_MESSAGES_REQUEST: 'GET_CHAT_WITH_MESSAGES_REQUEST',
    GET_CHAT_WITH_MESSAGES_SUCCESS: 'GET_CHAT_WITH_MESSAGES_SUCCESS',
    GET_CHAT_WITH_MESSAGES_ERROR: 'GET_CHAT_WITH_MESSAGES_ERROR',
    GET_USER_DATA_REQUEST: 'GET_USER_DATA_REQUEST',
    GET_USER_DATA_SUCCESS: 'GET_USER_DATA_SUCCESS',
    GET_USER_DATA_ERROR: 'GET_USER_DATA_ERROR',
    NOTIFICATION:'NOTIFICATION'
}